# display(df.loc[df['lost_B7'] == True, ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())
display(len(df.loc[df['lost_B7'] == True, ['ho_state_B7','ho_type_B7']]))
display(df.loc[df['lost_B7'] == True, ['ho_state_B7','ho_type_B7']].value_counts())
display(df.loc[(df['lost_B7'] == True) & (df['lost_B8'] == False), ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())
display(df.loc[df['lost_B7_B8'] == True, ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())

# display(df.loc[df['lost_B8'] == True, ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())
display(len(df.loc[df['lost_B8'] == True, ['ho_state_B8','ho_type_B8']]))
display(df.loc[df['lost_B8'] == True, ['ho_state_B8','ho_type_B8']].value_counts())
display(df.loc[(df['lost_B8'] == True) & (df['lost_B7'] == False), ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())
display(df.loc[df['lost_B7_B8'] == True, ['ho_state_B7','ho_type_B7','ho_state_B8','ho_type_B8']].value_counts())